### ISSUE TITLE
rules can be created with more than one "then" statement

### ISSUE THREAD

**Issue by manfred-kaiser** [manfred-kaiser/business-rule-engine#12]
It's not intended that a rule can have multiple ``then`` statements.

```
rule "order new items urgent"
when
    products_in_stock < 5,
then
    order_more(10)
then
    order_more(50)
end
```

**Comment by earthedalien** [comment]
Using AND(action_1,action_2) can only return True or False, when there is a need to capture return values from actions what to do?

**Comment by manfred-kaiser** [comment]
if you need multiple return values, you can define a custom function.

In this example I have created a lambda funciton, which converts all arguments to a list.

```python
from business_rule_engine import RuleParser

rules = """
rule "order new items"
when
    x < y
then
    TOARRAY(SUM(x,y), MAX(x, y))
end
"""

params = {
    'x': 2,
    'y': 5
}

parser = RuleParser()
parser.register_function(lambda *args: list(args), 'TOARRAY')
parser.parsestr(rules)
for rule in parser:
    rvalue_condition, rvalue_action = rule.execute(params)
    if rule.status:
        print("Sum of x+y: {}".format(rvalue_action[0]))
        print("Max value: {}".format(rvalue_action[1]))
        break
```

**Comment by earthedalien** [comment]
Manfred, thank you for sharing this! However, it compromises the readability of the rules for business users which is one of the major requirements in most cases. Therefore either multiple then statements or some other approach should be considered to avoid losing readability.

**Comment by manfred-kaiser** [comment]
Your suggested change from #11 does not work without code changes.

I have created a custom function ``printtext`` to print the given argument.

This rule will result in an error:

```pascal
rule "order new items"
when
    x < y
then
    printtext(1 + 1)
then
    printtext(2 + 2)
end
```
The reason is, that the parser concatenates both action in a single action ``printtext(1 + 1)printtext(2 + 2)``. The new rule is not valid.

This can get even worse, when you want to calculate some values:

```pascal
rule "order new items"
when
    x < y
then
    1 + 1
then
    2 + 2
end
```
The rules are valid and can be executed. You expect two values "2" and "4" but you are getting one value "15".


If you want to execute multiple custom functions, you can use ``;`` to separate multiple actions. But you will only get the last result.

```pascal
rule "order new items"
when
    x < y
then
    printtext(1 + 1); printtext(2 + 2)
end
```


I will change the parser, so that only one ``then`` is allowed, because the first example does not result in a valid rule.

**Comment by earthedalien** [comment]
I understand that bypassing formulas lib for actions would break existing code, I should create a fork in that case which would support multiple async actions where each action can return values.

**Comment by manfred-kaiser** [comment]
If you only want to execute some function on specific conditions and your conditions are simple value comparisons, you don't need the business-rule-engine.

The power of this library is, that it can even execute custom functions inside conditions.

In this example, a custom function ``get_items_count_from_db()`` is used to read values from the database.

```pascal
rule "order new items"
when
    get_items_count_from_db() < 10
then
    order_items(100)
end
```

If you want to support async functions, you should also support them in the conditions. At the moment, ``formulas`` does not support them.

There is another project with similar syntax: https://github.com/laurenz-sp/business-rules2

The project is also available on pypi: https://pypi.org/project/business-rules2/

Implementing async functions in that project is easier.

**Comment by manfred-kaiser** [comment]
If you want to contribute to my project, please create a new issue ticket, where we can discuss the implementation.

I will close this issue ticket, because implementing async function is off topic in this thread and the duplicate ``then`` was fixed.
